(()=>{'use strict';const cloud=KBRCloud,key='kbr_inventory_pending_v1',backupKey='kbr_inventory_before_cloud_v1';let revision=0,role='',ready=false,busy=false,polling=false,timer;const originalSave=saveInventory;const note=document.getElementById('cloudNote'),shell=document.getElementById('appShell'),retry=document.getElementById('cloudRetryBtn');
function cups(){}
const syncButton=document.getElementById('onlineStatus');
function connection(connected,label){syncButton.classList.toggle('connected',connected);syncButton.title=label;syncButton.setAttribute('aria-label',label);}
async function syncNow(){if(busy||polling)return;syncButton.disabled=true;try{if(!ready){await start();}else{clearTimeout(timer);await flush();if(cloud.read(key))return;await poll();if(syncButton.classList.contains('connected')){render();showToast('Inventory synced with Supabase.');}}}finally{syncButton.disabled=false;}}
syncButton.onclick=syncNow;
window.addEventListener('offline',()=>connection(false,'Offline — sync inventory'));

function lock(){shell.inert=!ready||busy||!!cloud.read(key)||!['owner','operator'].includes(role);retry.hidden=!cloud.read(key)||busy;}
function backup(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function apply(row){revision=row.revision;inventory=structuredClone(row.items);originalSave();render();cups();connection(true,'Cloud connected — sync inventory');note.textContent='Shared inventory saved · '+formatDateTime(row.updated_at);}
async function previous(){const rows=await cloud.request('/rest/v1/kbr_inventory_snapshots?select=day,items&order=day.desc&limit=1');if(rows[0])localStorage.setItem(PREVIOUS_KEY,JSON.stringify({date:rows[0].day,items:rows[0].items}));}
async function flush(){if(busy||polling||!ready)return;const op=cloud.read(key);if(!op)return;busy=true;lock();note.textContent='Saving inventory to Supabase…';try{const row=await cloud.rpc('kbr_save_inventory',op);if(row.conflict){localStorage.setItem('kbr_inventory_conflict_v1',JSON.stringify(op));localStorage.removeItem(key);const rows=await cloud.request('/rest/v1/kbr_inventory_state?id=eq.1&select=*');if(rows[0])apply(rows[0]);note.textContent='';showToast('Inventory changed on another device. Shared counts loaded.');}else{apply(row);localStorage.removeItem(key);await previous().catch(()=>{});}}catch(e){connection(false,'Change waiting — retry sync');note.textContent='Change waiting to sync: '+e.message+' Use Retry sync. Counts are saved on this device, but not yet confirmed in the cloud.';}finally{busy=false;lock();}}
saveInventory=(data=inventory)=>{originalSave(data);cups();if(!ready)return;const pending={p_items:structuredClone(data),p_expected_revision:revision,p_operation:cloud.uuid()};localStorage.setItem(key,JSON.stringify(pending));connection(false,'Change waiting — sync inventory');note.textContent='Local change saved · waiting to sync';clearTimeout(timer);timer=setTimeout(flush,700);};
// Keypad entry remains enabled while the 700 ms debounce collects digits.
async function poll(){if(!ready||busy||polling||cloud.read(key)||document.hidden)return;polling=true;try{const rows=await cloud.request('/rest/v1/kbr_inventory_state?id=eq.1&select=revision');if(rows[0]&&rows[0].revision!==revision){const full=await cloud.request('/rest/v1/kbr_inventory_state?id=eq.1&select=*');if(full[0]&&!cloud.read(key)){apply(full[0]);if(selectedId){keypadValue='';updateEditor(inventory.find(i=>i.id===selectedId));}}}await previous().catch(()=>{});connection(true,'Cloud connected — sync inventory');}catch(e){connection(false,'Cloud disconnected — retry sync');}finally{polling=false;if(cloud.read(key))flush();}}
async function start(){shell.inert=true;if(!cloud.requireLogin())return;try{if(!localStorage.getItem(backupKey))localStorage.setItem(backupKey,JSON.stringify({savedAt:new Date().toISOString(),items:inventory,previous:cloud.read(PREVIOUS_KEY)}));role=await cloud.role();const rows=await cloud.request('/rest/v1/kbr_inventory_state?id=eq.1&select=*');if(!rows.length){note.textContent=role==='owner'?'On the device with your latest counts, choose Publish this inventory once.':'Ask the owner to publish the latest inventory first.';if(role==='owner'){const button=document.createElement('button');button.textContent='Publish this inventory';button.onclick=async()=>{button.disabled=true;ready=true;localStorage.setItem(key,JSON.stringify({p_items:structuredClone(inventory),p_expected_revision:0,p_operation:cloud.uuid()}));await flush();if(revision>0)button.remove();};note.append(' ',button);}return;}
const pending=cloud.read(key);if(pending){revision=pending.p_expected_revision;inventory=pending.p_items;originalSave();render();cups();note.textContent='A saved inventory change needs confirmation. Use Retry sync.';}else apply(rows[0]);ready=true;retry.onclick=flush;await previous().catch(()=>{});lock();
// Add new seed entries without modifying existing stock counts.
if(!pending&&role==='owner'){const ids=new Set(inventory.map(i=>i.id)),added=freshInventoryFromSeed().filter(i=>!ids.has(i.id));if(added.length){inventory.push(...added);saveInventory();render();}}
}catch(e){connection(false,'Cloud disconnected — retry sync');note.textContent='Could not connect: '+e.message;retry.hidden=false;retry.onclick=start;}}
retry.onclick=flush;document.getElementById('backupBtn').onclick=()=>backup({format:'kbr-inventory-backup-v1',exportedAt:new Date().toISOString(),items:inventory,previous:cloud.read(PREVIOUS_KEY),beforeCloud:cloud.read(backupKey),pending:cloud.read(key),conflictingEdit:cloud.read('kbr_inventory_conflict_v1')},'KBR-inventory-backup.json');document.getElementById('signOutBtn').onclick=()=>{if(cloud.read(key)){note.textContent='Sync the pending change before signing out.';return;}cloud.logout();};window.addEventListener('online',()=>cloud.read(key)?flush():poll());window.addEventListener('focus',poll);setInterval(poll,10000);cups();start();
})();
