(()=>{'use strict';
const cloud=KBRCloud,queueKey='kbr_inventory_count_queue_v2',cacheKey='kbr_inventory_count_cache_v2',roleKey='kbr_inventory_count_role_v2',oldSave=saveInventory;
const shell=document.getElementById('appShell'),note=document.getElementById('cloudNote'),button=document.getElementById('onlineStatus'),retry=document.getElementById('cloudRetryBtn');
let base=cloud.read(cacheKey),busy=false,editing=false,timer,role=localStorage.getItem(roleKey)||'',legacyPending=cloud.read('kbr_inventory_pending_v1');
let queue=cloud.read(queueKey,[]),draft=cloud.read('kbr_inventory_count_draft_v2',[]);
function persist(){localStorage.setItem(queueKey,JSON.stringify(queue));localStorage.setItem('kbr_inventory_count_draft_v2',JSON.stringify(draft));}
function status(text,connected=false){button.classList.toggle('connected',connected);button.title=text;button.setAttribute('aria-label',text);note.textContent=text;retry.hidden=!queue.length&&!draft.length;}
function project(row){const f=row.countFields||{};const i=structuredClone(row);if(isPackaging(i)){i.stockBreakdown={...getPackagingValues(i),...Object.fromEntries(Object.entries(f).filter(([k])=>['frontPacks','frontSingles','backPacks'].includes(k)))};i.stock=packagingTotal(i);}else i.stock=Number(f.frontStock??i.stock??0)+Number(f.backStock??0);for(const k of ['supplier','threshold','orderStatus'])if(k in f)i[k]=f[k];return i;}
function apply(){if(!base)return;const rows=structuredClone(base.items);for(const op of [...queue,{p_changes:draft}])for(const c of op.p_changes||[]){const i=rows.find(i=>i.id===c.id);if(i)i.countFields={...i.countFields,[c.field]:c.value};}inventory=rows.map(project);oldSave();if(!editing){render();if(selectedId)updateEditor(inventory.find(i=>i.id===selectedId));}}
function changes(data){const prior=new Map(inventory.map(i=>[i.id,i])); // Compare with the projected saved image, since app mutates inventory in place.
const before=cloud.read('kbr_inventory_count_last_v2',[]);const lookup=new Map(before.map(i=>[i.id,i]));
for(const i of data){const old=lookup.get(i.id);if(!old)continue;const fields=isPackaging(i)?getPackagingValues(i):{frontStock:i.countFields?.frontStock??i.stock,backStock:i.countFields?.backStock??0};Object.assign(fields,{supplier:i.supplier,threshold:i.threshold,orderStatus:i.orderStatus??false});
for(const [field,value] of Object.entries(fields)){const oldVal=['frontPacks','frontSingles','backPacks'].includes(field)?getPackagingValues(old)[field]:['frontStock','backStock'].includes(field)?(old.countFields?.[field]??(field==='frontStock'?old.stock:0)):(old[field]??(field==='orderStatus'?false:null));if(JSON.stringify(value)===JSON.stringify(oldVal))continue;const existing=draft.find(c=>c.id===i.id&&c.field===field);if(existing)existing.value=value;else {const b=base?.items.find(b=>b.id===i.id);const pending=[...queue].reverse().flatMap(o=>o.p_changes||[]).find(c=>c.id===i.id&&c.field===field);draft.push({id:i.id,field,value,expected:pending?pending.value:(b?.countFields?.[field]??null)});}}}
}
function remember(){localStorage.setItem('kbr_inventory_count_last_v2',JSON.stringify(inventory));}
function seal(){if(draft.length){queue.push({p_operation:cloud.uuid(),p_changes:draft});draft=[];persist();}}
saveInventory=(data=inventory)=>{changes(data);oldSave(data);remember();persist();status('Counts saved on this device · waiting to sync');editing=true;clearTimeout(timer);timer=setTimeout(()=>{editing=false;seal();sync();},1800);};
async function sync(){if(busy||navigator.onLine===false){status('Offline · counts saved on this device');return;}busy=true;try{role=await cloud.role();localStorage.setItem(roleKey,role);if(!['owner','operator'].includes(role))throw Error('Staff access required');shell.inert=false;
if(!base){const rows=await cloud.request('/rest/v1/kbr_inventory_counts?id=eq.1&select=*');if(!rows[0])throw Error('Run the new inventory SQL first.');base=rows[0];}
while(queue.length){const op=queue[0];if(op.completeAfterSync){const dirty=base.items.filter(i=>i.countDirty);if(!dirty.length){queue.shift();persist();continue;}op.p_versions=dirty.map(i=>({id:i.id,version:i.countVersion}));delete op.completeAfterSync;persist();}const r=await cloud.rpc(op.p_versions?'kbr_complete_inventory_counts':'kbr_patch_inventory_counts',op);if(r.conflict){base=r.state;localStorage.setItem(cacheKey,JSON.stringify(base));status('Another device edited the same field. Your count is retained. Press Retry to review.');retry.onclick=()=>{if(!confirm('Use your saved values for these conflicting fields? '+r.fields.join(', ')))return;for(const c of op.p_changes)c.expected=base.items.find(i=>i.id===c.id)?.countFields?.[c.field]??null;op.p_operation=cloud.uuid();persist();sync();};apply();return;}base=r;queue.shift();persist();localStorage.setItem(cacheKey,JSON.stringify(base));}
if(!editing&&!draft.length){const rows=await cloud.request('/rest/v1/kbr_inventory_counts?id=eq.1&select=*');if(rows[0])base=rows[0];localStorage.setItem(cacheKey,JSON.stringify(base));apply();remember();}const previous=await cloud.request('/rest/v1/kbr_inventory_snapshots?select=day,items&order=day.desc&limit=1');if(previous[0])localStorage.setItem(PREVIOUS_KEY,JSON.stringify({date:previous[0].day,items:previous[0].items}));status('Counts synced · live usage is shown on the manager page',true);retry.onclick=()=>{seal();sync();};
}catch(e){status('Saved on this device · '+e.message);retry.hidden=false;}finally{busy=false;}}
const complete=document.createElement('button');complete.textContent='Complete inventory';complete.type='button';note.after(complete);complete.onclick=async()=>{seal();if(!queue.length&&!base?.items.some(i=>i.countDirty)){showToast('No new counts to complete.');return;}if(!confirm('Complete the shared inventory after your saved counts sync? Listed syrups: minus 150 ml. Listed powders and coffee beans: minus 320 g. Applied once to the combined front + back count.'))return;queue.push({p_operation:cloud.uuid(),completeAfterSync:true});persist();if(navigator.onLine===false){status('Inventory completion saved · will sync when online');return;}await sync();};
button.onclick=()=>{seal();sync();};retry.onclick=button.onclick;document.getElementById('backupBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({items:inventory,base,queue,draft,legacyPending},null,2)],{type:'application/json'}));a.download='KBR-inventory-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000);};document.getElementById('signOutBtn').onclick=()=>{if(queue.length||draft.length){showToast('Sync saved counts before signing out.');return;}cloud.logout();};
if(!cloud.requireLogin())return;if(base){shell.inert=false;apply();remember();status('Saved inventory ready · connecting…');}else{shell.inert=false;remember();status('Connect once to load shared counts.');}
window.addEventListener('online',()=>{seal();sync();});window.addEventListener('offline',()=>status('Offline · counts saved on this device'));window.addEventListener('focus',()=>{if(!editing)sync();});window.addEventListener('pagehide',seal);setInterval(()=>{if(!editing&&!document.hidden)sync();},5000);sync();
})();
